Introduce Bethe Free Energy
biaslab/RxInfer.jl pull request #173
Opened 2023-10-27 11:44 UTC by ThijsvdLaar

This branch includes an introduction to the Bethe Free Energy in the docs. Fixes #152 and #95.

2023-10-30 09:50 UTC, bvdmitri commented on docs/src/library/bethe-free-energy.md
> +A functional is the mathematical term for a function of a function that returns a scalar.
Are these spaces between the sentences intentional? Markdown starts a new paragraph if there is a blank line (as Latex)

2023-10-30 09:50 UTC, bvdmitri commented on docs/src/library/bethe-free-energy.md
> +A functional is the mathematical term for a function of a function that returns a scalar.
![Screenshot 2023-10-30 at 10 50 12](https://github.com/biaslab/RxInfer.jl/assets/6557701/eb6fb308-bc43-4386-ac3a-eb0f5eebe685)

2023-10-30 09:52 UTC, bvdmitri commented on docs/src/library/bethe-free-energy.md
> +$$q(x) \approx \frac{\prod_a q_a(x_a)}{\prod_i q_i(x_i)^{d_i - 1}}\,.$$
Why `\approx`? Shouldn't it be just `=` as its our own choice

2023-10-30 09:52 UTC, bvdmitri commented on docs/src/library/bethe-free-energy.md
> +$$q(x) \approx \frac{\prod_a q_a(x_a)}{\prod_i q_i(x_i)^{d_i - 1}}\,.$$
What is `d_i`

2023-10-30 09:56 UTC, bvdmitri commented on docs/src/library/bethe-free-energy.md
> +Crucially, the BFE can be iteratively optimized for each individual variational distribution in turn. Optimization of the BFE is thus more manageable than direct optimization of the VFE. However, the
This line is a bit confusing,  the optimization of VFE and BFE entails an approximation, which is not always exact in both cases.

2023-10-30 09:59 UTC, bvdmitri commented on docs/src/library/bethe-free-energy.md
> +For iterative optimization of the BFE, the variational distributions must first be initialized. The `initmarginals` function initializes the variational distributions of the BFE.
The `initmarginals` is not a function, but a keyword argument to the `inference` and `rxinference` function. You can use 
```
[`inference`](@ref) or [`rxinference`](@ref)
```
to generate links to their respective documentation.

2023-10-30 10:04 UTC, bvdmitri requested changes
Thanks @ThijsvdLaar! It's a good start, but there are a couple of comments I would like to be addressed before we can merge this. I noticed that some sentences are separated with blank lines and some are not, that makes a difference in the generated HTML file. 

For preview you can use `make docs` or `julia --project=docs docs/make.jl` (for the second command don't forget to initialize the `docs` environment). Either of these commands will generate HTML files in the `build` folder. Also you can check this small [guide](https://biaslab.github.io/RxInferDevGuides.jl/dev/guides/docs-contributing/#Use-[LiveServer.jl](https://github.com/tlienart/LiveServer.jl)).

 The PR also sais that it fixes the confusion between priors and initial marginals, but I didn't find that explanation in the text. For the rest look at my comments. Thanks!

@ismailsenoz can you also take a look (and perhaps add something from your side?)

2023-10-30 11:27 UTC, ThijsvdLaar commented
Thanks for the feedback, I've made some changes to address your concerns.

@ismailsenoz might have more to say on these matters.

2023-10-31 07:51 UTC, ismailsenoz reviewed
I think it looks good. This level of detail is enough imo. It is a good summary @ThijsvdLaar. Maybe there is one thing that can be added. If the user chooses a constraint involving variables that are not argument to common factors it will be ignored by the inference engine due to Bethe assumption. There is always implicit Bethe constraints that the user should always be aware of.

2023-10-31 08:50 UTC, bvdmitri commented
> If the user chooses a constraint involving variables that are not argument to common factors it will be ignored by the inference engine due to Bethe assumption. There is always implicit Bethe constraints that the user should always be aware of

I think this guide should not be a guide about `@constraints`, the guide about `@constraints` is a separate documentation page and we should keep in mind to mention it there https://github.com/biaslab/RxInfer.jl/issues/150

2023-10-31 13:17 UTC, bvdmitri reviewed
Thanks @ThijsvdLaar ! I like the text, the only thing which I think can be added is a list of relevant links to papers/materials for further reading. Feel free to add anything to the list what you find relevant. Then I can merge.

2023-10-31 15:02 UTC, ThijsvdLaar commented
@bvdmitri I've added some of my go-to papers.

2023-10-31 15:04 UTC, bvdmitri approved these changes
Great, thanks!

2023-10-31 15:05 UTC, bvdmitri commented
Lets see if tests are still passing......😁

2023-10-31 16:23 UTC, merged